package main

import (
	"flag"

	"github.com/fabriziosestito/go-stub-package/pkg/gen"
)

func main() {
	flag.Parse()

	err := gen.GenerateStubs(flag.Args())
	if err != nil {
		panic(err)
	}
}

// // check if it's a generated file
// func isGeneratedFile(file *ast.File) bool {
// 	const lookupStr1 = "code generated by" // keep this string lower-cased
// 	const lookupStr2 = "do not edit"       // and this one either

// 	for _, commentsGroup := range file.Comments {
// 		for _, comment := range commentsGroup.List {
// 			if len(comment.Text) < len(lookupStr1) {
// 				continue
// 			}

// 			lowerComment := strings.ToLower(comment.Text)
// 			if strings.Contains(lowerComment, lookupStr1) &&
// 				strings.Contains(lowerComment, lookupStr2) {
// 				return true
// 			}
// 		}
// 	}

// 	return false
// }
